### ISSUE TITLE
[FR]: PTP unregistered API

### ISSUE THREAD

**Issue by jp8311** [StuffAnThings/qbit_manage#101]
### Is your feature request related to a problem? Please elaborate.

PTP requires a lot of manual input for management of deregistered torrents due to trumps.

I installed this not realising the api script was specific to BHD

### Describe the solution you'd like

Updating the unregistered torrent options to include PTP UR API

### Does your solution involve any of the following?

- [ ] New config option
- [ ] New command option

### Describe alternatives you've considered

I had a look at the script and suspect it would be transferable to PTP API for unregistered torrents. I'm just not clever enough to make a commit myself.

### Who will this benefit?

Anyone using qbittorrent via webui knows there's no simple way to filter unregistered torrents, they still appear to be seeding.

There doesn't seem to be an elegant fix currently for Radarr/Sonarr users.

**Comment by bobokun** [comment]
This should not be required. PTP uses standardized naming so the remove unregistered should work on PTP just fine. I haven't seen any issues of not catching unregistered torrents with PTP. BHD was an exception since they don't standardize their torrent error message making it difficult to identify unregistered torrents.
