### ISSUE TITLE
[FR]: enhance Cross Seed Webhook to add the Tracker of the new xseed

### ISSUE THREAD

**Issue by bakerboy448** [StuffAnThings/qbit_manage#103]
### Is your feature request related to a problem? Please elaborate.

Title

currently one does not know when a cross seed is added what tracker it is for

### Describe the solution you'd like

Add more details to the webhook

### Does your solution involve any of the following?

- [ ] New config option
- [ ] New command option

### Describe alternatives you've considered

Xseed notifications but don't want those 

### Who will this benefit?

Xseed users

### Additional Information

👋

**Comment by bobokun** [comment]
The problem is when [adding the torrent](https://qbittorrent-api.readthedocs.io/en/latest/apidoc/torrents.html?highlight=add#qbittorrentapi.torrents.TorrentsAPIMixIn.torrents_add) I don't know what tracker it's coming from. To add the torrent it doesn't return me any information about the torrent it only returns "OK" for success or "Fails" if it failed to add.

**Comment by bakerboy448** [comment]
Anyway to circle back or to scrape from the torrent file itself?

**Comment by bobokun** [comment]
Probably will have to add the torrent first and then look up the new added torrent to determine the tracker

**Comment by bobokun** [comment]
Without complicating things would it be okay if I get the tracker from the filename coming from cross-seed? That way I don't need to loop back after adding. This causes complications for dry-run as well (looping back won't work since the torrent doesn't actually get added in dry-run).
