### ISSUE TITLE
[FR]: Remove all Cross-Seed torrents if the original is deleted

### ISSUE THREAD

**Issue by thezak48** [StuffAnThings/qbit_manage#148]
### Is your feature request related to a problem? Please elaborate.

When I delete a torrent and it's files if there are cross-seeds for that torrent too they get left behind until I notice them

### Describe the solution you'd like

If torrent and it's files are deleted, delete all torrents that are also cross-seeding those files

### Does your solution involve any of the following?

- [X] New config option
- [ ] New command option

### Describe alternatives you've considered

Custom script but that seems like work that I no wanna do

### Who will this benefit?

All Cross-Seed users

**Comment by bobokun** [comment]
Currently this functionality is sorta implemented via hardlinks, if Radarr upgrades a movie, the previous torrent would no longer be hardlinked and therefore all cross-seeds would be removed eventually via noHL.

Regarding your FR, how would qbm know which file is the "original" torrent? If you do remove an original torrent manually, there isn't really any way for qbm to know that you deleted an original torrent or cross seed.

**Comment by KyleSanderson** [comment]
> Regarding your FR, how would qbm know which file is the "original" torrent? If you do remove an original torrent manually, there isn't really any way for qbm to know that you deleted an original torrent or cross seed.

This very kind person filed the FR for me, so I'll weigh in.

I'd love to use the product, the current issue is if you remove a cross-seeded torrent this orphans the data for the rest. So the solution is incredibly simple (that I wrote my own solution for) - if the name matches, group them all, and treat the weakest one (lowest ratio/time/etc) as the one to be scored.

**Comment by thezak48** [comment]
Another addition is to check if the data is even there, if not then the original has been deleted so it's safe to delete the cross-seeds

**Comment by quorn23** [comment]
> Regarding your FR, how would qbm know which file is the "original" torrent? If you do remove an original torrent manually, there isn't really any way for qbm to know that you deleted an original torrent or cross seed.

The one without the cross-seed tag. If only one has no cross-seed tag, it's the original, would that work?

**Comment by bobokun** [comment]
> The one without the cross-seed tag. If only one has no cross-seed tag, it's the original, would that work?

We can't generalize that everyone tags cross-seeded torrents with a cross-seed tag, not everyone who uses qbm will have a setup like this.

> I'd love to use the product, the current issue is if you remove a cross-seeded torrent this orphans the data for the rest. So the solution is incredibly simple (that I wrote my own solution for) - if the name matches, group them all, and treat the weakest one (lowest ratio/time/etc) as the one to be scored.

If you manually delete a torrent with contents, all the cross-seeded torrents should end up with errors since the files will be missing. I'm trying to understand better what the use case of removing the cross-seeded torrents are. Is it to remove any broken that have files missing?

Do you mind sharing the solution that you created so that I can better understand the use case?

**Comment by KyleSanderson** [comment]
s := fmt.Sprintf("%s%s%s%04d%02d%02d%02d%03d", rls.MustNormalize(r.Artist), rls.MustNormalize(r.Title), rls.MustNormalize(r.Subtitle), r.Year, r.Month, r.Day, r.Series, r.Episode)

Then from there scan the torrent list, if they all match (including Cut / Edition / etc), then treat them as the same.

**Comment by 2fst4u** [comment]
Wouldn't it be best to leave all torrents, regardless of if they're a cross seed or not, to be left to their respective tracker settings in qbitmanage? If tracker A requires 2 week seed time and tracker B has a cross seedable target 13 days after you've been seeding, and they also have a minimum seed time, don't you want the cross seeded version to still seed even if the original has been fulfilled and since removed?

Assuming none of these torrents have hardlinks anymore.

Shouldn't this be left up to the orphaned torrents feature to pick up orphaned data once both versions are no longer seeding?

**Comment by bakerboy448** [comment]
There won't be any orphaned data as when the torrents are removed the corresponding data would be.

but yes seeding to the tracker's mins makes sense as well

**Comment by 2fst4u** [comment]
Doesn't this raise the question that torrents shouldn't have their corresponding data removed then? Only the torrent should be removed and not data, and when it's orphaned then the orphaned data function will fix it.

**Comment by bakerboy448** [comment]
Probably would make more sense to adjust the logic and remove data if and only if it's the last torrent (if it doesn't already work that way)

**Comment by bobokun** [comment]
> Probably would make more sense to adjust the logic and remove data if and only if it's the last torrent (if it doesn't already work that way)

The current logic is set to do this 👍

**Comment by KyleSanderson** [comment]
> > Probably would make more sense to adjust the logic and remove data if and only if it's the last torrent (if it doesn't already work that way)
> 
> The current logic is set to do this 👍

it doesn't though, because the other units of work are deleted and there's no grouping of them. Carlitos artifact does it more scientifically than mine, where the actual contents are compared to generate the dependency graph.

**Comment by bobokun** [comment]
I currently use qbit_manage with cross seeds and it works fine without deleting any of the data until there's only one torrent left without any orphan files. 

This is the part of the code logic that does the check.

https://github.com/StuffAnThings/qbit_manage/blob/6b6001ec0ee576ecb905546c737a7b9222717075/modules/qbittorrent.py#L746-L760

**Comment by KyleSanderson** [comment]
> I currently use qbit_manage with cross seeds and it works fine without deleting any of the data until there's only one torrent left without any orphan files.
> 
> This is the part of the code logic that does the check.
> 
> https://github.com/StuffAnThings/qbit_manage/blob/6b6001ec0ee576ecb905546c737a7b9222717075/modules/qbittorrent.py#L746-L760

Yes, that's understood. However, I'm sure you can understand that it's a bit (for others, very) silly to do that as the load isn't on having the torrents in client, but on the disk itself. Having another entry to maintain tracker stats costs a couple kb of RAM and the torrent file on disk. The data itself is where the "expense" is here. Keeping around the other units of work is, comparatively speaking, free, which is the desired goal of the feature request.

**Comment by Schaka** [comment]
I read the entire discussion and I still can't seem to figure out if there's already some sort of solution or something way simpler (as an option) would suffice.

For me, personally, I handle torrent durations by their original grab. This makes sense to me, because different trackers have different values, rules, priorities, etc.

However, when an "original" torrent's requirements are met, it will then get cleaned up (torrent and files deleted). This will lead to any possible cross-seed that's left behind starting a new download. 
If there was an optional step that deleted all torrents that do NOT point to an existing file/folder, right after the cleanup, it would solve my issue and now delete the orphaned torrent files.

I can't really think of a nice way to name things - but since we're calling files without a torrent orphans - what's a torrent without a file? Childless?

**Comment by bakerboy448** [comment]
> when an "original" torrent's requirements are met, it will then get cleaned up (torrent and files deleted). This will lead to any possible cross-seed that's left behind starting a new download.

QBm does not delete data that is still in use (I.e. same path) as existing torrents

**Comment by KyleSanderson** [comment]
> I read the entire discussion and I still can't seem to figure out if there's already some sort of solution or something way simpler (as an option) would suffice.
> 
> For me, personally, I handle torrent durations by their original grab. This makes sense to me, because different trackers have different values, rules, priorities, etc.
> 
> However, when an "original" torrent's requirements are met, it will then get cleaned up (torrent and files deleted). This will lead to any possible cross-seed that's left behind starting a new download. If there was an optional step that deleted all torrents that do NOT point to an existing file/folder, right after the cleanup, it would solve my issue and now delete the orphaned torrent files.
> 
> I can't really think of a nice way to name things - but since we're calling files without a torrent orphans - what's a torrent without a file? Childless?

It took about 20 minutes of effort from start to finish: upgraderr doesn't have this bug.

**Comment by Schaka** [comment]
> It took about 20 minutes of effort from start to finish: upgraderr doesn't have this bug.

Sorry for asking here, but is there any documentation? 
I have qbit trigger cross-seed atm and it would be somewhat easy to just trigger upgraderr - but not for complete searches if I add a new tracker to the "rotation2. 

Lastly, how does this solve the issue of cleanup? qbm would still delete file and torrent when cleaning up and not catch the cross-seeds. I could imagine getting around qbm's cross-seed detection via symlinks for your cross-seeded torrents, but I can't see how they would get cleaned up in the end.

Thanks for taking the time.

**Comment by bakerboy448** [comment]
https://github.com/StuffAnThings/qbit_manage/wiki/Config-Setup#share_limits

> Lastly, how does this solve the issue of cleanup? qbm would still delete file and torrent when cleaning up 

I don't believe you read the answer.....again the data is not deleted if there are xseeds

**Comment by Schaka** [comment]
I guess I'll have to write my own cleanup code or adjust Carlito's code then.
At this point, cross-seeds will never get cleaned up because they seed infinitely.

If I don't cross-seed infinitely, torrents then get cleaned up on per-tracker share limits and cross-seed will likely add them back if one tracker is set to seed 2-3 months and another is set to 2 weeks.

Anyway, thanks for the explanation. I can probably think of a way to make this work.

**Comment by tordenflesk** [comment]
> cross-seed will likely add them back if one tracker is set to seed 2-3 months and another is set to 2 weeks.

Cross-seed doesn't re-add, only of you wipe its data.

**Comment by KyleSanderson** [comment]
> > It took about 20 minutes of effort from start to finish: upgraderr doesn't have this bug.
> 
> Sorry for asking here, but is there any documentation? I have qbit trigger cross-seed atm and it would be somewhat easy to just trigger upgraderr - but not for complete searches if I add a new tracker to the "rotation2.
> 
> Lastly, how does this solve the issue of cleanup? qbm would still delete file and torrent when cleaning up and not catch the cross-seeds. I could imagine getting around qbm's cross-seed detection via symlinks for your cross-seeded torrents, but I can't see how they would get cleaned up in the end.
> 
> Thanks for taking the time.

I gave up on waiting and literally spent 20 minutes on the solution 😆. The author of this issue was kind enough to open it for me when I explained the original problem, which has still not been resolved.

use qbittools with orphaned to cleanup the data on disk. upgraderr won't remove dupes from the client until they all meet the expression. This is very trivial to fix. If you don't want to use qbittools I can open up another tool to do it.

Also feel free to ignore bakerboy, he literally just follows from issue to issue and has zero development experience with worthless feedback. It's very disappointing.

**Comment by ahatdude** [comment]
Hey all,
I was going to create a new thread, but I think this one is essentially stating my issue as well. 
The problem:

- After sonarr upgrades from episodes to a season pack or upgrades episodes themselves, the original downloaded content gets deleted by qbit as it should be, however if in the meantime cross-seed has found matches on other platforms and those torrents are active, the content will actually never be deleted unless I do a manual sweep (currently in the lengthy process of doing this).

I'm not sure if this is something that can be fixed with qbitmanage in its current state or this is something that is being worked on (or not).

Thanks for your time.

**Comment by bakerboy448** [comment]
Excluding Kyle or other off topic commentary. Can any users provide specific use cases with specific non-working share_limits that do not resolve this at this point in time?

**Comment by ahatdude** [comment]
> Excluding Kyle or other off topic commentary. Can any users provide specific use cases with specific non-working share_limits that do not resolve this at this point in time?


Tracker A has a movie that is grabbed by radarr.
Once the download finishes, cross-seeds are found in tracker B and C.
In 2 days, this movie is removed from tracker A because a better version has been found.
The better version is grabbed and is now used in radarr as the default one.
The first version from tracker A is now tagged as noHL and the torrent will get removed.
However, the cross-seed torrents are still active and seeding in tracker B and C and I believe those will remain in the torrent client.

I believe this is the process, however ideally once the original torrent is deleted so should its contents as well as the cross seeding torrents. This avoids having many versions of the same media occupying space unecessarily, since most of us really only care about having the best possible version on our servers.

I could be missing something, so please let me know if there is a way to avoid this using share_limits.

**Comment by bakerboy448** [comment]
> with **specific non-working share_limits** that do not resolve this at this point in time?

provide the share limits being used and not working. NoHL and cross-seed tags in a share limit group should easily accomplish that

**Comment by bobokun** [comment]
@ahatdude , this can definitely be achieved with share limits.
> The first version from tracker A is now tagged as noHL and the torrent will get removed.

When tracker A is tagged as noHL, those cross seeds from tracker B and C will also be tagged as noHL, so your cross-seeds will also be deleted alongside tracker A at the same time. 

If you want the cross-seeds to have a different share limit than tracker A, you can always create another share limit with a much smaller max_seeding_time to capture those torrents using the filter: `include_all_tags: [noHL, cross-seed]`

**Comment by bakerboy448** [comment]
That config file is invalid and has been invalid for awhile. You're failing to use sharelimits thus nothing will ever be removed and no seed targets will ever be set.  Redo your file.

**Comment by ahatdude** [comment]
> That config file is invalid for v4+ and has been [invalid for almost a year](https://github.com/StuffAnThings/qbit_manage/releases/tag/v4.0.0). You're failing to use sharelimits thus nothing will ever be removed and no seed targets will ever be set. Redo your file.
> 
> why are you ignoring what you were told to do? Use share_limits and are doing absolutely nothing at all with them?

Alright, thanks for your help.

**Comment by bobokun** [comment]
Closing this as share_limits should cover this use case.
