### ISSUE TITLE
[FR] - Seed Goals per Tracker / Per Category

### ISSUE THREAD

**Issue by bakerboy448** [StuffAnThings/qbit_manage#30]
Title

**Comment by Drazzilb08** [comment]
As discussed in #22 
Separate topic welcomed to keep things clean.

**Comment by bobokun** [comment]
This feature is now implemented in Develop branch. Can you please help test? 
See the new `config.yml.sample` on how to configure seed goals/limits by tracker.

Please note that this will only change the seeding goal/upload limit when it tags a new torrent. In order to test this feature you must untag the torrents you want to test and use run the script with `--tag-update` in order to change the seeding goal/limit for the tag. Once tagged it will no longer check seeding goals/limits.
