### ISSUE TITLE
[FR] Docker image

### ISSUE THREAD

**Issue by SamuelCook** [StuffAnThings/qbit_manage#33]
I'd love to consume this as a Docker image. Any plans to create one and publish to Docker Hub or another public image repo?

**Comment by bobokun** [comment]
I haven't created a docker image before but I'll look into it.

**Comment by SamuelCook** [comment]
I had a go at making my own version - take a look at https://github.com/SamuelCook/docker-qbit_manage / https://hub.docker.com/repository/docker/samuelcook/qbit_manage. It's quick and dirty but it does the job.

If you create an official version I'll probably just delete my repos.

**Comment by bobokun** [comment]
Hey thanks so much for your contribution! I was actually working on this all weekend since I am new to building docker I'm still learning a lot. So far it seems to be working well and I've pushed the change to development branch and on dockerhub as well. Please take a look and let me know if there are ways to improve my process. Thanks! I won't close this FR until this gets moved to master. Hopefully soon

**Comment by SamuelCook** [comment]
Nice! It looks great. Feel free to post Docker questions in this thread, I'd be happy to help however I can.
