### ISSUE TITLE
[FR] Automatic Category Assignment

### ISSUE THREAD

**Issue by berot3** [StuffAnThings/qbit_manage#50]
Basically this: https://github.com/qbittorrent/qBittorrent/issues/5779 (open)

I guess qbit will never have this build in.

When is this useful: for ex. when adding a torrent manually and not category was giving. Instead of manually selecting a category this could be done by simple rules. See issue from above for more.

**Comment by bobokun** [comment]
In the newest develop branch I have it set the default category based on it's saved path if it's not defined in the config. Example: If you manually download a torrent and it's saved in /data/torrents/Movies and your config.yml doesn't have a Movie category it will automatically add the Movie category in your config for you.

In terms of file pattern, not sure if that's really feasible because what if there are multiple files in the torrent? What if multiple categories match with the rules you set?

**Comment by leo-carmo** [comment]
Too bad the idea on #5779 is not coming through, at least apparently :(
