### ISSUE TITLE
[Bug]: Share limit tags do not update

### ISSUE THREAD

**Issue by akesher123** [StuffAnThings/qbit_manage#500]
### Describe the Bug

This is the same as #457. I didn't see a way to re-open that issue, so feel free to close this and re-open that one. 

For me the issue described in #457 persists with 4.0.9. Any torrent with the `MinSeedTimeNotReached` tag will not have its share limits updated. It will erroneously have the tag for my noHL groups, however something else in the code knows that it is not noHL because the torrents do not get removed.

### Logs

https://gist.github.com/akesher123/d7f00b29745f1457da0c82b1a46ba484

### Installation

Unraid

### Version Number

4.0.9

### What branch are you on?

master

**Comment by bobokun** [comment]
Logs show you are running 4.0.6. Please also post your config

**Comment by akesher123** [comment]
Sorry, those were the old logs. Here is are the logs from a previous run
https://gist.github.com/akesher123/00f002775bd634417cedaf5e3a46ddea

Here's a run immediately after adding those tags to `ignoreTags_OnUpdate`.
https://gist.github.com/akesher123/a174ae314930d98fead136483599b592

**Comment by bakerboy448** [comment]
Config?

**Comment by akesher123** [comment]
Oops, forgot 

https://privatebin.net/?cb75ab9064331ebe#LozvxG28aXi4YswxzwXbQyFr7czSi7gTp9rVgB9yijk

**Comment by bobokun** [comment]
I've added some additional checks for invalid configurations in the latest develop https://github.com/StuffAnThings/qbit_manage/commit/9202f7eec4268eacc6dd1d31d18fa1c98b93af0a . This is a configuration issue. Please reread the wiki for an explanation on the share_limits and hop on discord if you need any additional help. 

You probably are looking for `max_seeding_time` instead of `min_seeding_time`
