### ISSUE TITLE
[FR]: Tag torrent by release group (or search string)

### ISSUE THREAD

**Issue by Zenya393** [StuffAnThings/qbit_manage#514]
### Is your feature request related to a problem? Please elaborate.

I want to tag torrents by release group.

### Describe the solution you'd like

Potential Solutions:
1. Search torrent name for release group text defined in config.yml.
2. RegEx the release group from the torrent name. 

The 2nd option also would allow for tagging torrents for any kind of regex search criteria.

### Does your solution involve any of the following?

- [X] New config option
- [ ] New command option

### Describe alternatives you've considered

Manually tagging torrents.
Which also conflicts with ignoreTags_OnUpdate.

### Who will this benefit?

Anyone who wants to keep track and organize torrents by release group.
Anyone who wants to create tags for any regular expression.

**Comment by bakerboy448** [comment]
Why? What benefit does using tags to identify torrents by group provide? The UI can just be searched and provide the groups with partial string matches, no? 

this seems likely to be highly performance intensive 

as far as group specific - difficult due to poor torrent naming and many variations of group naming, even the Starrs have several variations of logic to attempt to  get the group, but often still can't and had to resort to a hardcoded list as a fallback
