### ISSUE TITLE
[FR]: Add Ability to Move Seeding Torrents to a Seeding Directory

### ISSUE THREAD

**Issue by HarryMuscle** [StuffAnThings/qbit_manage#94]
### Is your feature request related to a problem? Please elaborate.

Currently there are only a few possible places for a torrent to reside; in the completed category related directory, or in the incomplete directory.  Adding a third option for seeding torrents to reside in would help in sorting large numbers of torrents.  It would also help in being able to see at a glance (at the file system) what the current status is of the various torrents without having to log into qBittorrent 

For example, if you're seeding lots and lots of torrents it can be a pain to find the one torrent you just downloaded (and aren't seeding permanently) amongst all of the other torrents in the completed directory.

### Describe the solution you'd like

I think it would be a great feature to be able to move torrents that are being seeded to a seeding directory.  Once there are finished seeding they would then move to the completed directory.

### Does your solution involve any of the following?

- [x] New config option
- [ ] New command option

### Describe alternatives you've considered

I've started looking into scripting this myself but a solution built into qbit_manage would be way better.

### Who will this benefit?

Anyone who likes to keep their torrents organized or has lots of them in general.

**Comment by bobokun** [comment]
After reviewing the request I believe this is a functionality outside the scope of qBm as this would require qBm to constantly monitor qB in order to move the torrent to the proper category/directory. Furthermore this could result in unnecessary move commands back and forth between directories as torrents can pop in and out of "seeding" status very frequently depending on the tracker. 

I just don't feel this is the right fit for qBm.
