### ISSUE TITLE
QBittorrent Version

### ISSUE THREAD

**Issue by firestrife23** [StuffAnThings/qbit_manage#97]
### What is the improvement or update you wish to see?

I'm getting this error message about running the lastest version of qbittorrent:

`| Qbittorrent Error: qbit_manage is only comaptible with v4.3.* or lower. You are currently on v4.4.0 |`

May want to warn users about this, and will need to downgrade the qbittorrent, unless you are planning on updating qbit_manage to work with v4.4.0?

### Is there any context that might help us understand?

Just ask away if that's the case.

**Comment by bobokun** [comment]
Yes this is put intentionally so qbit_manage will not run for unsupported versions of qbittorrent. You can update to develop branch that is compatible with v4.4.0, or if you can wait a day or two I plan to push these changes to the master branch

**Comment by firestrife23** [comment]
I just updated to develop branch and all is well. Thank you.

**Comment by ftc2** [comment]
nbd, but two small things:

1. it would be nice to document the minimum supported version for each release
 just fyi, `hotio/qbittorrent:release-4.4.3.1` was too new for `hotio/qbitmanage:release-3.2.3`. i somehow expected it to work because of https://github.com/StuffAnThings/qbit_manage/commit/08133659b6560d07a94cd9f58febc58e61d30a39, but i guess that came after `3.2.3`?
2. typo in https://github.com/StuffAnThings/qbit_manage/blob/master/modules/qbittorrent.py#L32
 `/s/comaptible/compatible/` :)
